"""Auto-generate the block registries from the directory contents, so promoting a
block is just `mv raw/X.tsx library/X.tsx` + re-run this — no hand-editing index
files (which is where concurrent-edit bugs crept in).

Scans src/blocks/library/*.tsx and raw/*.tsx, reads EVERY `export const <Name>`
in each file (a file may export more than one block, e.g. ChapterCard+EndCard),
and writes library/index.ts (LIBRARY map), raw/index.ts (RAW map), and
blocks/index.ts (BLOCKS = {...LIBRARY, ...RAW}).

Usage: python web-video-lab/gen_registry.py
"""
from __future__ import annotations

import re
from pathlib import Path

BLOCKS = Path("render-service/_lab_chapter/src/blocks")
_EXPORT = re.compile(r"export const (\w+)\s*[:=]")


def _exports(d: Path) -> dict[str, list[str]]:
    """file stem -> list of exported component names (a file may export several)."""
    out: dict[str, list[str]] = {}
    for f in sorted(d.glob("*.tsx")):
        names = _EXPORT.findall(f.read_text(encoding="utf-8"))
        if names:
            out[f.stem] = names
    return out


def _write_map(d: Path, var: str) -> list[str]:
    ex = _exports(d)
    imports = "\n".join(f'import {{ {", ".join(names)} }} from "./{stem}";' for stem, names in ex.items())
    flat = [n for names in ex.values() for n in names]
    names = ", ".join(flat)
    head = "// AUTO-GENERATED by web-video-lab/gen_registry.py — do not edit by hand.\n"
    (d / "index.ts").write_text(f"{head}{imports}\n\nexport const {var} = {{ {names} }};\n", encoding="utf-8")
    return flat


def main() -> None:
    lib = _write_map(BLOCKS / "library", "LIBRARY")
    raw = _write_map(BLOCKS / "raw", "RAW")
    (BLOCKS / "index.ts").write_text(
        "// AUTO-GENERATED by web-video-lab/gen_registry.py — do not edit by hand.\n"
        'import { LIBRARY } from "./library";\n'
        'import { RAW } from "./raw";\n\n'
        "// library = cataloged/reusable; raw = bespoke one-offs. Same render engine.\n"
        "export const BLOCKS = { ...LIBRARY, ...RAW };\n",
        encoding="utf-8",
    )
    print(f"LIBRARY ({len(lib)}): {', '.join(sorted(lib))}")
    print(f"RAW ({len(raw)}): {', '.join(sorted(raw))}")


if __name__ == "__main__":
    main()
