// AUTO-GENERATED by web-video-lab/gen_registry.py — do not edit by hand.
import { LIBRARY } from "./library";
import { RAW } from "./raw";

// library = cataloged/reusable; raw = bespoke one-offs. Same render engine.
export const BLOCKS = { ...LIBRARY, ...RAW };
