# Venezuela Documentary Project
id: fcaa7aa9
name: Venezuela
description: Documentary about Hugo Chavez and Venezuela
created: 2026-01-14

# Source videos to index
source_videos:
  - source/videos/

# Output settings
output_dir: output/
assets_dir: assets/
