# Venezuela Documentary Project
id: 6c00244a
slug: venezuela
name: Venezuela Documentary
description: Documentary about Hugo Chavez and Venezuela
created: 2026-01-14

# Source videos to index
source_videos:
  - source/videos/

# Output settings
output_dir: output/
assets_dir: assets/
