// AUTO-GENERATED by web-video-lab/gen_registry.py — do not edit by hand.
import { ArchStack } from "./ArchStack";
import { AttentionFlow } from "./AttentionFlow";
import { NpcStrike } from "./NpcStrike";
import { SelfFeedingCurve } from "./SelfFeedingCurve";

export const RAW = { ArchStack, AttentionFlow, NpcStrike, SelfFeedingCurve };
