"""Build the bundle for a NOLAN design-system project on claude.ai/design.

Two deliverables:

1. `_adherence.oxlintrc.json` — the constraint config, GENERATED from what the gate actually
   enforces (`author.py::_RAW_SEEK_FORBIDDEN`) plus a theme's real `tokens.css`. Generated, never
   hand-written, because a hand-written copy is a second source of truth that drifts — the exact
   failure mode the organ-skill sync rule exists to prevent.

2. Card previews — real composed blocks, SEEKED past their reveals and frozen to static HTML.
   A NOLAN block at t=0 is blank, so naive publishing yields empty cards.

    python -X utf8 explore/2026-08-04-infographic/ds_seed.py --theme highlighter-editorial
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
BRIDGE = REPO / "render-service" / "_lab_hyperframes" / "bridge"

_CSS_VAR = re.compile(r"--([a-z0-9-]+)\s*:\s*([^;]+);")

# One frame per block so each publishes as its own card. Shapes copied from a spec that already
# renders (`bridge/scenes_spec.json`) rather than invented from the schema prose.
CARDS = [
    {
        "id": "statement", "dur": 8.0, "seek": 6.0, "group": "Prose",
        "scene": {"id": "s1", "type": "statement", "start": 0, "dur": 8.0,
                  "data": {"kicker": "THE CONTRACT", "register": "paper",
                           "lines": ["Narration owns duration —", "everything else follows."],
                           "operative": "duration", "cue": 3.6}},
    },
    {
        "id": "stat", "dur": 9.0, "seek": 7.0, "group": "Data",
        "scene": {"id": "s1", "type": "stat", "start": 0, "dur": 9.0,
                  "data": {"kicker": "THE VOCABULARY", "register": "paper",
                           "items": [{"from": 0, "to": 51, "label": "COMPOSER BLOCKS",
                                      "cue": 2.0, "underline": True}]}},
    },
    {
        "id": "chart", "dur": 9.0, "seek": 7.5, "group": "Data",
        "scene": {"id": "s1", "type": "chart", "start": 0, "dur": 9.0,
                  "data": {"kicker": "WHERE THE TIME GOES", "type": "bar",
                           "series": [{"label": "Author", "value": 34},
                                      {"label": "Resolve", "value": 21},
                                      {"label": "Compose", "value": 12},
                                      {"label": "Render", "value": 48}]}},
    },
]


def forbidden_needles() -> list[tuple[str, str]]:
    """The determinism rules the gate REALLY enforces, read from author.py so the two cannot drift."""
    src = (BRIDGE / "author.py").read_text(encoding="utf-8")
    m = re.search(r"_RAW_SEEK_FORBIDDEN\s*=\s*\[(.*?)\]", src, re.S)
    if not m:
        raise SystemExit("could not find _RAW_SEEK_FORBIDDEN in author.py — the generator is stale")
    pairs = re.findall(r'\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)', m.group(1))
    if not pairs:
        raise SystemExit("_RAW_SEEK_FORBIDDEN parsed empty — refusing to emit an empty rule set")
    return pairs


def theme_tokens(slug: str) -> list[str]:
    css = (REPO / "themes" / slug / "tokens.css").read_text(encoding="utf-8")
    return sorted({f"--{name}" for name, _ in _CSS_VAR.findall(css)})


def adherence(slug: str) -> dict:
    needles = forbidden_needles()
    tokens = theme_tokens(slug)
    restricted = [
        {"selector": f"Literal[value=/{re.escape(n)}/]",
         "message": f"{why} — the frame is ONE paused, seeked timeline (author.py rejects this)."}
        for n, why in needles
    ]
    restricted += [
        {"selector": r"Literal[value=/#[0-9a-fA-F]{3,8}\b/]",
         "message": f"Raw hex colour — use a NOLAN theme token via var(). NOLAN ships 41 themes; a "
                    f"literal follows none of them."},
        {"selector": r"Literal[value=/(filter|backdrop-filter|box-shadow)\s*:/]",
         "message": "transform_opacity_only — animate transform and opacity only."},
        {"selector": r"Literal[value=/\b(top|left|width|height)\s*:\s*[-0-9]/]",
         "message": "transform_opacity_only — layout properties re-flow per frame; use transform."},
    ]
    return {
        "plugins": ["import"],
        "rules": {"no-restricted-syntax": ["warn", *restricted]},
        "x-omelette": {
            "components": {},
            "tokens": tokens,
            "tokenKinds": {t: ("color" if t.startswith(("--shell", "--surface", "--text", "--accent", "--rule"))
                               else "font" if t.startswith("--font")
                               else "radius" if t.startswith("--r-")
                               else "spacing")
                           for t in tokens},
            "fontFamilies": [],
            "x-nolan": {
                "source": "generated by explore/2026-08-04-infographic/ds_seed.py",
                "enforced_by_gate": [n for n, _ in needles],
                "declared_but_unenforced": [
                    "transform_opacity_only", "caption_keep_out_83pct",
                    "sid_prefixed_ids", "no_exit_on_non_final", "duration_preserving",
                ],
            },
        },
    }


def build_cards(slug: str, out: Path) -> list[dict]:
    sys.path.insert(0, str(BRIDGE))
    import compose  # noqa: E402

    made = []
    for card in CARDS:
        fid = f"card-{card['id']}"
        html = compose.compose_frame(fid, card["dur"], [card["scene"]], theme=slug)
        raw = out / f"{fid}.raw.html"
        raw.write_text(html, encoding="utf-8")
        final = out / f"{card['id']}.html"
        r = subprocess.run(
            ["node", str(HERE / "snapshot.mjs"), str(raw), fid, str(card["seek"]), str(final)],
            cwd=str(HERE), capture_output=True, text=True,
        )
        line = (r.stderr.strip().splitlines() or ["(no output)"])[-1]
        print(f"{'ok  ' if r.returncode == 0 else 'FAIL'} {card['id']:10} {line}")
        if r.returncode == 0:
            made.append({**card, "path": f"components/{card['id']}.html"})
    return made


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--theme", default="highlighter-editorial")
    ap.add_argument("--out", default=str(HERE / "_ds"))
    args = ap.parse_args()

    out = Path(args.out)
    (out / "components").mkdir(parents=True, exist_ok=True)

    cfg = adherence(args.theme)
    (out / "_adherence.oxlintrc.json").write_text(json.dumps(cfg, indent=2), encoding="utf-8")
    print(f"adherence: {len(cfg['rules']['no-restricted-syntax']) - 1} rules, "
          f"{len(cfg['x-omelette']['tokens'])} tokens from {args.theme}")

    made = build_cards(args.theme, out / "components")
    (out / "readme.md").write_text(
        "# NOLAN blocks\n\n"
        "Composer blocks from `render-service/_lab_hyperframes/bridge/compose.py`, each SEEKED past\n"
        "its reveals and frozen. A NOLAN block's timeline is created paused and animates content in\n"
        "from nothing, so at t=0 every card would be blank.\n\n"
        "`_adherence.oxlintrc.json` is GENERATED from `author.py::_RAW_SEEK_FORBIDDEN` plus the\n"
        f"theme's `tokens.css` (`{args.theme}`). Do not hand-edit it.\n",
        encoding="utf-8")

    print(f"\n{len(made)}/{len(CARDS)} cards built into {out}")
    return 0 if len(made) == len(CARDS) else 1


if __name__ == "__main__":
    sys.exit(main())
